package mgpkg

import (
	"mirage-go/cmd"
	"mirage-go/core"
	"strings"

	"github.com/shotastage/GFileable"
)

func Bootstrap() {
	println("Initializing MIRAGE package...")
	GFileable.Touch("Mgfile")

	print("Type project name: ")
	pjname := core.StrStdin()

	print("Type your name: ")
	name := core.StrStdin()

	print("Type version: ")
	version := core.StrStdin()

	print("Type programming language: ")
	lang := core.StrStdin()

	file := GFileable.Path("./Mgfile")
	file.WriteString(":* This file is generated by Mirage Go *:\n")
	file.WriteString(makeLine("name=", pjname))
	file.WriteString(makeLine("author=", name))
	file.WriteString(makeLine("version=", version))
	file.WriteString(makeLine("language=", lang))

	cmd.Sess.Exec()
}

func makeLine(str ...string) string {
	return strings.Join(str, "") + "\n"
}
